services:
  # 1. База данных
  db:
    image: postgres:15-alpine
    container_name: stl_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: stl_viewer_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: stl_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: rootpassword
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. Бэкенд
  server:
    build: ./server
    container_name: stl_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_HOST=db  # Оставляем db, это имя сервиса выше
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=rootpassword
      - DB_NAME=stl_viewer_db
    volumes:
      - ./server/storage:/app/storage
    depends_on:
      - db

  # 4. Фронтенд
  client:
    build: ./client
    container_name: stl_client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server